name: Flutter CI

on:
  workflow_call:

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.44.6
          cache: true

      - name: Run CI checks
        run: ./scripts/ci.sh
